// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoAxEai5WoiRuKJTu5zxOTiZt4uEIoN8',
    appId: '1:481127102779:web:d9cac1b68c650d1a7f1f1e',
    messagingSenderId: '481127102779',
    projectId: 'fb-statenf-auth-815',
    authDomain: 'fb-statenf-auth-815.firebaseapp.com',
    storageBucket: 'fb-statenf-auth-815.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdMO-IifaFcgOfHP7G7FymBhbOROTqK2g',
    appId: '1:481127102779:android:566ec4deda88c32d7f1f1e',
    messagingSenderId: '481127102779',
    projectId: 'fb-statenf-auth-815',
    storageBucket: 'fb-statenf-auth-815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZ9a5pBWjAvNJiPc0S5qEMC1dgs6PT4A',
    appId: '1:481127102779:ios:21c4f08f8a2d8c167f1f1e',
    messagingSenderId: '481127102779',
    projectId: 'fb-statenf-auth-815',
    storageBucket: 'fb-statenf-auth-815.appspot.com',
    iosClientId: '481127102779-jruoikp055hb4ame53ub60bpc224sg72.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZ9a5pBWjAvNJiPc0S5qEMC1dgs6PT4A',
    appId: '1:481127102779:ios:d23b9f2b8f8140937f1f1e',
    messagingSenderId: '481127102779',
    projectId: 'fb-statenf-auth-815',
    storageBucket: 'fb-statenf-auth-815.appspot.com',
    iosClientId: '481127102779-i90dj9aalualstopctgc57996h861906.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthProvider.RunnerTests',
  );
}
